/**
 * `codex-panel` — the host half of the Codex panel.
 *
 * The browser cannot reach host-only facts (login state, the skills this bridge
 * rejected, the MCP servers it skipped) through any existing remote, and the
 * typed-remote system is generated by a toolchain this deployment does not
 * ship. The settings service, however, is already exposed to the browser and
 * already carries host-owned values — so this row registers one small
 * `codex-bridge` namespace holding a *summary* (never the 88-entry list; that
 * comes from the existing `skills/list` remote) and refreshes it on boot and
 * whenever the skill catalog changes.
 *
 * The browser half lives in the sibling `dsh-codex-bridge-client` package: a
 * client bundle must be the *only* Loader row resolving to its package name
 * (`client-modules` rejects two sources for one client package), while this
 * package is mounted through four host rows. Keep the two apart.
 *
 * Read-only with respect to Codex: it reads Codex's files and writes only this
 * Harness-side namespace.
 *
 * @module dsh-codex-bridge/panel
 */
import Schema from '@deepseek-ai/schemastery'
import { collectCodexStatus } from './status.js'

/** Cordis plugin name. */
export const name = 'codex-panel'
/** The settings service this row publishes the panel summary into. */
export const inject = ['settings']

/** Settings namespace the panel reads. */
export const PANEL_NAMESPACE = 'codex-bridge'

const StatusSchema = Schema.object({
  authState: Schema.string().default('unknown'),
  authMode: Schema.string().default(''),
  authDetail: Schema.string().default(''),
  skillsUsable: Schema.number().default(0),
  skillsSkipped: Schema.number().default(0),
  mcpServers: Schema.number().default(0),
  mcpSkipped: Schema.number().default(0),
  skillsSkippedReasons: Schema.array(Schema.string()).default([]),
  mcpSkippedReasons: Schema.array(Schema.string()).default([]),
  generatedAt: Schema.string().default('')
})

/**
 * Collect the panel summary and write it into the `codex-bridge` namespace.
 *
 * The write is a wholesale `replace`, not a merge: this namespace is a
 * last-collection-wins snapshot, so a stale key surviving a refresh (a reason
 * line that no longer applies, a count from a previous collector) would be the
 * panel contradicting itself. `replace` also makes every field explicit — the
 * card never has to reason about which fields an earlier write happened to set.
 *
 * Every rejection the panel would have to explain is written to the log as
 * well: the panel shows counts plus the reason lines, and `tail`-style analysis
 * of the backend log is where debugging belongs.
 *
 * @param {object} ctx - Cordis context carrying `settings`, `tools`, and `logger`.
 * @param {object} settings - the registered settings service (`ctx.settings`).
 * @param {object} [config] - `{ codexHome?, cwd? }`.
 * @returns {Promise<void>} settlement after the namespace write.
 */
export async function refreshCodexPanel(ctx, settings, config = {}) {
  try {
    const toolNames = ctx.get?.('tools')?.schemas?.().map((schema) => schema.name) ?? []
    const status = await collectCodexStatus({
      codexHome: config.codexHome,
      cwd: config.cwd,
      logger: ctx.logger,
      toolNames
    })
    await settings.replace(PANEL_NAMESPACE, {
      authState: status.auth.state,
      authMode: status.auth.authMode ?? '',
      authDetail: status.auth.detail,
      skillsUsable: status.skills.usable.length,
      skillsSkipped: status.skills.skipped.length,
      mcpServers: status.mcp.servers.length,
      mcpSkipped: status.mcp.skipped.length,
      skillsSkippedReasons: status.skills.skipped.map((skill) => `${skill.path}: ${skill.reason}`),
      mcpSkippedReasons: status.mcp.skipped.map((server) => `${server.name}: ${server.reason}`),
      generatedAt: status.generatedAt
    })
    for (const skill of status.skills.skipped) {
      ctx.logger?.info?.(`codex-panel: skill rejected — ${skill.path}: ${skill.reason}`)
    }
    for (const server of status.mcp.skipped) {
      ctx.logger?.info?.(`codex-panel: mcp skipped — ${server.name}: ${server.reason}`)
    }
  } catch (error) {
    ctx.logger?.warn?.(`codex-panel: status refresh failed: ${String(error)}`)
  }
}

/**
 * Register the panel namespace and keep its summary current.
 * @param {object} ctx - Cordis context carrying `settings` and `tools`.
 * @param {object} [config] - `{ codexHome?, cwd? }`.
 */
export function apply(ctx, config = {}) {
  ctx.inject(['settings'], (settingsCtx) => {
    settingsCtx.settings.register(PANEL_NAMESPACE, StatusSchema)
    const refresh = () => refreshCodexPanel(ctx, settingsCtx.settings, config)
    void refresh()
    ctx.on?.('skills/change', () => {
      void refresh()
    })
  })
}
